language: php

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=4.4.*
    - php: 7.2
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*

install:
  - php ./tests/symfony-version.php "$SYMFONY_VERSION"
  - composer install
  - composer show

test:
  - ./vendor/bin/phpunit


